// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://golpmciubzlkzpbqfowo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdvbHBtY2l1Ynpsa3pwYnFmb3dvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwNjEzNzcsImV4cCI6MjA2MDYzNzM3N30.xhw5USh_rAL932yb0ELl8CAto_I4VQ0AvjNQ9MHcHeU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);